#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : libwnck3
Version  : 43.2
Release  : 40
URL      : https://download.gnome.org/sources/libwnck/43/libwnck-43.2.tar.xz
Source0  : https://download.gnome.org/sources/libwnck/43/libwnck-43.2.tar.xz
Summary  : Window Navigator Construction Kit library
Group    : Development/Tools
License  : LGPL-2.0
Requires: libwnck3-bin = %{version}-%{release}
Requires: libwnck3-data = %{version}-%{release}
Requires: libwnck3-lib = %{version}-%{release}
Requires: libwnck3-license = %{version}-%{release}
Requires: libwnck3-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(libstartup-notification-1.0)
BuildRequires : pkgconfig(xres)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libwnck
=======
libwnck is Window Navigator Construction Kit, i.e. a library to use
for writing pagers and taskslists and stuff.

%package bin
Summary: bin components for the libwnck3 package.
Group: Binaries
Requires: libwnck3-data = %{version}-%{release}
Requires: libwnck3-license = %{version}-%{release}

%description bin
bin components for the libwnck3 package.


%package data
Summary: data components for the libwnck3 package.
Group: Data

%description data
data components for the libwnck3 package.


%package dev
Summary: dev components for the libwnck3 package.
Group: Development
Requires: libwnck3-lib = %{version}-%{release}
Requires: libwnck3-bin = %{version}-%{release}
Requires: libwnck3-data = %{version}-%{release}
Provides: libwnck3-devel = %{version}-%{release}
Requires: libwnck3 = %{version}-%{release}

%description dev
dev components for the libwnck3 package.


%package lib
Summary: lib components for the libwnck3 package.
Group: Libraries
Requires: libwnck3-data = %{version}-%{release}
Requires: libwnck3-license = %{version}-%{release}

%description lib
lib components for the libwnck3 package.


%package license
Summary: license components for the libwnck3 package.
Group: Default

%description license
license components for the libwnck3 package.


%package locales
Summary: locales components for the libwnck3 package.
Group: Default

%description locales
locales components for the libwnck3 package.


%prep
%setup -q -n libwnck-43.2
cd %{_builddir}/libwnck-43.2
pushd ..
cp -a libwnck-43.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736887764
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/libwnck3
cp %{_builddir}/libwnck-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libwnck3/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang libwnck-3.0
## install_append content
mkdir -p %{buildroot}/V3/usr/bin
mv %{buildroot}/usr/bin/wnck-urgency-monitor %{buildroot}/usr/bin/wnck-urgency-monitor-3
mv %{buildroot}/usr/bin/wnckprop %{buildroot}/usr/bin/wnckprop-3
mv %{buildroot}-v3/usr/bin/wnck-urgency-monitor %{buildroot}/V3//usr/bin/wnck-urgency-monitor-3
mv %{buildroot}-v3/usr/bin/wnckprop %{buildroot}/V3//usr/bin/wnckprop-3
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/wnck-urgency-monitor-3
/V3/usr/bin/wnckprop-3
/usr/bin/wnck-urgency-monitor-3
/usr/bin/wnckprop-3

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Wnck-3.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libwnck-3.0/libwnck/application.h
/usr/include/libwnck-3.0/libwnck/class-group.h
/usr/include/libwnck-3.0/libwnck/icons.h
/usr/include/libwnck-3.0/libwnck/libwnck.h
/usr/include/libwnck-3.0/libwnck/misc.h
/usr/include/libwnck-3.0/libwnck/pager.h
/usr/include/libwnck-3.0/libwnck/resource.h
/usr/include/libwnck-3.0/libwnck/screen.h
/usr/include/libwnck-3.0/libwnck/selector.h
/usr/include/libwnck-3.0/libwnck/tasklist.h
/usr/include/libwnck-3.0/libwnck/util.h
/usr/include/libwnck-3.0/libwnck/version.h
/usr/include/libwnck-3.0/libwnck/window-action-menu.h
/usr/include/libwnck-3.0/libwnck/window.h
/usr/include/libwnck-3.0/libwnck/wnck-enum-types.h
/usr/include/libwnck-3.0/libwnck/wnck-handle.h
/usr/include/libwnck-3.0/libwnck/workspace.h
/usr/lib64/libwnck-3.so
/usr/lib64/pkgconfig/libwnck-3.0.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libwnck-3.so.0.3.0
/usr/lib64/libwnck-3.so.0
/usr/lib64/libwnck-3.so.0.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libwnck3/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files locales -f libwnck-3.0.lang
%defattr(-,root,root,-)

